# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=256, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u7ba1\u7406\u5458',
            },
        ),
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('idAdminInfo', models.AutoField(default=b'', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, verbose_name=b'user_name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'admin_info',
                'permissions': (('admin_role', 'Is an Admin'),),
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=64, verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7\xe5\x90\x8d\xe7\xa7\xb0')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=64, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('idCourseInfo', models.AutoField(default=b'', primary_key=True, serialize=False)),
                ('cname', models.CharField(default=b'', max_length=15, verbose_name=b'course_name')),
                ('lhour', models.IntegerField(default=0, verbose_name=b'learning_hour')),
                ('credit', models.IntegerField(default=0, verbose_name=b'credit')),
                ('semester', models.CharField(default=b'', max_length=15, verbose_name=b'semester')),
            ],
            options={
                'verbose_name': 'CourseInfo',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name=b'\xe8\x80\x83\xe8\xaf\x95\xe5\x88\x86\xe6\x95\xb0')),
                ('title', models.CharField(blank=True, max_length=1024, null=True, verbose_name=b'\xe4\xb8\xbb\xe9\xa2\x98')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Course', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe8\xaf\xbe\xe7\xa8\x8b')),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u8003\u8bd5',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
            ],
            options={
                'verbose_name': '\u5b66\u9662',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=64, verbose_name=b'\xe4\xb8\x93\xe4\xb8\x9a\xe5\x90\x8d\xe7\xa7\xb0')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Institute', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe5\xad\xa6\xe9\x99\xa2')),
            ],
            options={
                'verbose_name': '\u4e13\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=256, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('the_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Class', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x8f\xad\xe7\xba\xa7')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(default=0, verbose_name=b'grade')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CourseInfo', verbose_name=b'course')),
            ],
            options={
                'verbose_name': 'student_course',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('idStudentInfo', models.AutoField(default=b'', primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=6, verbose_name=b'student_name')),
                ('sex', models.CharField(max_length=2, verbose_name=b'sex')),
                ('bdate', models.DateTimeField(verbose_name=b'birthdata')),
                ('dept', models.CharField(max_length=8, verbose_name=b'department')),
                ('classno', models.CharField(max_length=15, verbose_name=b'class number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'student_info',
                'permissions': (('student_role', 'Is a Student'),),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=256, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Major', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe4\xb8\x93\xe4\xb8\x9a')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x94\xa8\xe6\x88\xb7')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
            },
        ),
        migrations.CreateModel(
            name='TeacherClassShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Admin', verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe8\x80\x85')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Teacher', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe6\x95\x99\xe5\xb8\x88')),
                ('the_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Class', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x8f\xad\xe7\xba\xa7')),
            ],
            options={
                'verbose_name': '\u6559\u5e08\u73ed\u7ea7\u5173\u7cfb',
            },
        ),
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CourseInfo', verbose_name=b'course')),
            ],
            options={
                'verbose_name': 'teacher_course',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('idTeacherInfo', models.AutoField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=6, verbose_name=b'teacher_name')),
                ('sex', models.CharField(max_length=2, verbose_name=b'sex')),
                ('dept', models.CharField(max_length=8, verbose_name=b'department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'user')),
            ],
            options={
                'verbose_name': 'teacher_info',
                'permissions': (('teacher_role', 'Is a Teacher'),),
            },
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.TeacherInfo', verbose_name=b'teacher'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.StudentInfo', verbose_name=b'student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Student', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe5\xad\xa6\xe7\x94\x9f'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Teacher', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe6\x95\x99\xe5\xb8\x88'),
        ),
        migrations.AddField(
            model_name='course',
            name='the_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Class', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe7\x8f\xad\xe7\xba\xa7'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Major', verbose_name=b'\xe6\x8c\x87\xe5\xae\x9a\xe4\xb8\x93\xe4\xb8\x9a'),
        ),
    ]
